#ifndef QMQSERVICESRC_GLOBAL_H
#define QMQSERVICESRC_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QMQSERVICESRC_LIBRARY)
#  define QMQSERVICESRCSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QMQSERVICESRCSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QMQSERVICESRC_GLOBAL_H
