#ifndef HTTPBASEDONCURL_GLOBAL_H
#define HTTPBASEDONCURL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HTTPBASEDONCURL_LIBRARY)
#  define HTTPBASEDONCURLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define HTTPBASEDONCURLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HTTPBASEDONCURL_GLOBAL_H
