#ifndef QMQSERVICECOMMONUSE_GLOBAL_H
#define QMQSERVICECOMMONUSE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QMQSERVICECOMMONUSE_LIBRARY)
#  define QMQSERVICECOMMONUSESHARED_EXPORT Q_DECL_EXPORT
#else
#  define QMQSERVICECOMMONUSESHARED_EXPORT Q_DECL_IMPORT
#endif

#include <QMap>
#include <QVariant>

#endif // QMQSERVICECOMMONUSE_GLOBAL_H
