#ifndef FINSUDPSERVICE_GLOBAL_H
#define FINSUDPSERVICE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FINSUDPSERVICE_LIBRARY)
#  define FINSUDPSERVICESHARED_EXPORT Q_DECL_EXPORT
#else
#  define FINSUDPSERVICESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FINSUDPSERVICE_GLOBAL_H
