#ifndef QMELSECUDPCLIENT_GLOBAL_H
#define QMELSECUDPCLIENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QMELSECUDPCLIENT_LIBRARY)
#  define QMELSECUDPCLIENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QMELSECUDPCLIENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QMELSECUDPCLIENT_GLOBAL_H
